import type { FontFormat } from "./types.js";

export interface InstallInstructionsInput {
  inputUrl: string;
  inputType: "googleFontsCss" | "website";
  discoveredFontCssUrls: string[];
  families: string[];
  prefix?: string;
  formats?: FontFormat[];
}

export function generateInstallInstructions(input: InstallInstructionsInput): string {
  const prefix = input.prefix ?? "./fonts/";
  const cssPath = "./fonts.css";
  const formats = input.formats?.length ? input.formats.join(", ") : "woff2, woff, ttf";
  const families = input.families.length > 0 ? input.families.join(", ") : "(selected fonts)";

  const lines = [
    "Google Fonts Localizer — Self-Hosting Installation Guide",
    "Generated by gfont-localize",
    "",
    "This guide explains how to replace Google Fonts with locally hosted files.",
    "",
    "=== Source ===",
    "",
    `Analyzed URL: ${input.inputUrl}`,
    `Input type: ${input.inputType === "website" ? "Website page scan" : "Direct Google Fonts CSS URL"}`,
    `Font families in this export: ${families}`,
    `Formats included: ${formats}`,
    "",
    "=== ZIP contents ===",
    "",
    "  fonts.css       — @font-face rules pointing to ./fonts/",
    "  test.html       — Local preview page to verify fonts load",
    "  LICENSE-SUMMARY.txt — License status for each family",
    "  INSTALL.md      — This file",
    "  fonts/          — Downloaded font binaries",
    "",
    "=== Installation steps ===",
    "",
    "1. Download the ZIP and extract it into your project (e.g. public/fonts-bundle/ or assets/fonts/).",
    "",
    "2. Upload the extracted folder to your web server so fonts.css and fonts/ are publicly reachable.",
    "",
    `3. Add this stylesheet link to your HTML <head> (adjust the path to match where you uploaded the files):`,
    "",
    `   <link rel="stylesheet" href="${cssPath}">`,
    "",
  ];

  if (input.inputType === "website" && input.discoveredFontCssUrls.length > 0) {
    lines.push(
      "4. Remove or comment out the existing Google Fonts <link> tags from your site:",
      ""
    );
    for (const url of input.discoveredFontCssUrls) {
      lines.push(`   <!-- Remove: ${url} -->`);
    }
    lines.push(
      "",
      "   Search your HTML templates, CMS theme files, and CSS @import rules for fonts.googleapis.com.",
      ""
    );
    lines.push(
      "5. Ensure your CSS still references the same font-family names. The generated fonts.css uses the original Google Fonts family names, so existing styles should continue to work.",
      "",
      "6. Open test.html in a browser (via your local server, not file://) to confirm every variant loads.",
      "",
      "7. In Chrome DevTools → Network, filter by \"Font\" and reload your site. Requests should go to your domain, not fonts.gstatic.com or fonts.googleapis.com.",
      ""
    );
  } else {
    lines.push(
      "4. Remove any previous Google Fonts stylesheet link that loaded these families.",
      "",
      "5. Open test.html in a browser (via your local server) to confirm fonts load correctly.",
      "",
      "6. Verify in DevTools → Network that font requests hit your server, not Google CDN.",
      ""
    );
  }

  lines.push(
    "=== CSS path prefix ===",
    "",
    `Generated @font-face src paths use prefix: ${prefix}`,
    "If you move the fonts/ folder, re-export with a matching prefix or edit src URLs in fonts.css.",
    "",
    "=== Notes ===",
    "",
    "- Review LICENSE-SUMMARY.txt before using fonts in production.",
    "- This tool provides informational license hints only; it is not legal advice.",
    ""
  );

  return lines.join("\n");
}
