import { generateLicenseSummaryText, getSelectedFamilyLicenses } from "./fontLicense.js";
import { buildWebsiteReportPdfFilename } from "./generateWebsiteReportPdf.js";
import type {
  FontLicenseInfo,
  LlmResearchMeta,
  SelectableFontVariant,
  WebsiteReportInput,
} from "./types.js";

export type { WebsiteReportInput };

function formatLlmResearchSection(llmResearch?: LlmResearchMeta): string[] {
  if (!llmResearch?.requested) {
    return ["AI license research: not requested for this analysis."];
  }

  if (!llmResearch.active) {
    return ["AI license research: requested but not active (missing API URL or key)."];
  }

  const provider =
    llmResearch.provider === "gemini"
      ? "Google Gemini"
      : llmResearch.provider === "groq"
        ? "Groq"
        : "OpenAI-compatible API";

  const lines = [
    `AI license research: active (${provider})`,
    llmResearch.apiHost ? `API host: ${llmResearch.apiHost}` : "",
    llmResearch.model ? `Model: ${llmResearch.model}` : "",
    typeof llmResearch.llmCallCount === "number"
      ? `LLM API calls made: ${llmResearch.llmCallCount}`
      : "LLM API calls made: 0 (automatic detection handled all fonts)",
  ];

  return lines.filter(Boolean);
}

function formatVariantSummary(variants: SelectableFontVariant[]): string[] {
  if (variants.length === 0) {
    return ["(none)"];
  }

  const grouped = new Map<string, SelectableFontVariant[]>();
  for (const variant of variants) {
    const list = grouped.get(variant.family) ?? [];
    list.push(variant);
    grouped.set(variant.family, list);
  }

  const lines: string[] = [];
  for (const [family, familyVariants] of [...grouped.entries()].sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    lines.push(`  ${family} (${familyVariants.length} variant(s)):`);
    for (const variant of familyVariants) {
      const formats = Object.keys(variant.sources).join(", ") || "none";
      lines.push(
        `    - ${variant.subset} · weight ${variant.weight} · ${variant.style} [${formats}]`
      );
    }
  }
  return lines;
}

export function generateWebsiteReport(input: WebsiteReportInput): string {
  const selectedIds = input.selectedVariantIds ?? input.variants.map((v) => v.id);
  const selectedVariants = input.variants.filter((v) => selectedIds.includes(v.id));
  const selectedLicenses = getSelectedFamilyLicenses(
    input.familyLicenses,
    selectedIds,
    input.variants
  );
  const formats = input.formats?.length ? input.formats.join(", ") : "woff2, woff, ttf";

  const lines = [
    "Google Fonts Localizer — Website Font Report",
    "Generated by gfont-localize",
    "",
    "=== Overview ===",
    "",
    `Scanned URL: ${input.inputUrl}`,
    `Scan type: ${input.inputType === "website" ? "Website page" : "Direct Google Fonts CSS URL"}`,
    `Report generated: ${new Date().toISOString()}`,
    "",
    "=== Discovery ===",
    "",
    `Google Fonts CSS links found: ${input.discoveredFontCssUrls.length}`,
  ];

  if (input.discoveredFontCssUrls.length > 0) {
    lines.push("");
    for (const url of input.discoveredFontCssUrls) {
      lines.push(`  - ${url}`);
    }
  }

  lines.push(
    "",
    `Ignored direct gstatic font URLs: ${input.ignoredDirectFontAssetCount}`,
    `Total selectable variants: ${input.variants.length}`,
    `Selected variants for export: ${selectedVariants.length}`,
    `Export formats: ${formats}`
  );

  if (input.inputType === "website") {
    lines.push("");
    if (input.pageLang) {
      lines.push(`Page language: ${input.pageLang}`);
    }
    if (input.recommendedSubsets?.length) {
      lines.push(`Recommended subsets: ${input.recommendedSubsets.join(", ")}`);
    }
    if (input.scannedStylesheets?.length) {
      lines.push("", "Stylesheets scanned:", "");
      for (const sheet of input.scannedStylesheets) {
        lines.push(`  - ${sheet}`);
      }
    }
  }

  lines.push(
    "",
    "=== AI license research ===",
    "",
    ...formatLlmResearchSection(input.llmResearch),
    "",
    "=== All detected variants ===",
    "",
    ...formatVariantSummary(input.variants),
    "",
    "=== Selected variants (export scope) ===",
    "",
    ...formatVariantSummary(selectedVariants),
    "",
    "=== Migration checklist ===",
    "",
    "  [ ] Download ZIP with selected fonts",
    "  [ ] Upload fonts.css and fonts/ folder to your server",
    "  [ ] Add <link rel=\"stylesheet\" href=\"./fonts.css\"> to your HTML",
  );

  if (input.discoveredFontCssUrls.length > 0) {
    lines.push("  [ ] Remove Google Fonts <link> tags:");
    for (const url of input.discoveredFontCssUrls) {
      lines.push(`      - ${url}`);
    }
  }

  lines.push(
    "  [ ] Open test.html to verify fonts load locally",
    "  [ ] Confirm DevTools Network shows fonts from your domain",
    "  [ ] Review license summary below before production use",
    "",
    "=== License summary (selected families) ===",
    "",
    generateLicenseSummaryText(selectedLicenses),
    ""
  );

  return lines.join("\n");
}

export function buildWebsiteReportFilename(inputUrl: string): string {
  return buildWebsiteReportPdfFilename(inputUrl);
}
